### ISSUE TITLE
su-template

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/ruby-api-stubs#11]
Why is the su-template in this repository?  We should be running yard using the template in the template repo, not this one, right?

**Comment by thomthom** [comment]
That was something I recently played around with, including it here in the stubs now that the stubs act as a way to get user contributions. I was thinking that making people pull two different repos, and then instruct them on configuring things to all link up was a bit annoying. So I added to the stub build process to copy over the yard templates so one can just pull the one repo and hit `yardoc`.

That leaves us with some duplication. 

So if people don't want to have the yard template and config in one repo we can take it out again. Otherwise, if that seem to be preferable we can remove the other yard-template repo.

What's your thoughts on this?

**Comment by jimfoltz** [comment]
I prefer to  have the stubs and template in the same (stubs) repo.  As you say, it will simplify the workflow for contributors. Lowering barriers is a good thing.  

How do you ensure the template in `ruby-api-stubs` always matches the latest `sketchup-yard-template` version?

**Comment by jimfoltz** [comment]
Are you generating the online docs from the c++ source or the stubs?  

It seems most of the stuff in `sketchup-yard-template` is for internal use, and is not useful for documentation contributors.

**Comment by thomthom** [comment]
So at the moment I copy the template into the stubs repo as part of the build: https://github.com/SketchUp/sketchup-yard-template/blob/master/tools/thor/stubs.rb#L42

I think with the current `sketchup-yard-template` repo I've so far manually keps it up to date by copy+paste. I have been meaning to automate that, but if we go with using the stubs repo for it all then it'd be redundant.

@DanRathbun what is your thoughts on this? Consolidating the stubs and yard template we use to generate the docs. That way we have less repos to keep up with and one less issue tracker. (We'd off course have to transfer the open issues.)

**Comment by jimfoltz** [comment]
Is it a problem then if the template gets updated in the `stubs` repo, would tou need to manually copy the changes to the `sketchup-yard-template` repo?

**Comment by thomthom** [comment]
> Are you generating the online docs from the c++ source or the stubs?

From the C++ source.

> It seems most of the stuff in `sketchup-yard-template` is for internal use, and is not useful for documentation contributors.

Yea, I can probably exclude the custom templates we use ourself. It's the `default` sub-folder which is the custom template for the docs.

That being said, the stubs template use just use the YARD database, so you could use that tempate yourself to generate stubs out of anything.

**Comment by thomthom** [comment]
> Is it a problem then if the template gets updated in the stubs repo, would you need to manually copy the changes to the sketchup-yard-template repo? Or would you just move that entire template out of the sketchup-yard-template repo to the stubs repo?

I think that if we're ok with just using this repo to retire the other `sketchup-yard-template` all together. Because at the moment it's only purpose is to generate Yard docs using our custom template.

**Comment by DanRathbun** [comment]
> but if we go with using the stubs repo for it all then it'd be redundant. ...
> I think that if we're ok with using only this repo, the we can retire the other sketchup-yard-template all together. 

**Disagree !** Template Issues are separate and beyond many Ruby scripters cares (or understanding in most cases.)

The template repo is a good place to log issues that will affect **only the template**. There we can discuss nitty YARD details that will only confuse the Ruby coders concerned only with the output.

**Comment by thomthom** [comment]
We could create a project in the issue tracker for template related issues?

If we keep the stubs and template separate then there is extra setup needed to get things running. I was hoping to minimize this.

**Comment by DanRathbun** [comment]
> @DanRathbun what is your thoughts on this? Consolidating the stubs and yard template we use to generate the docs. That way we have less repos to keep up with and one less issue tracker. (We'd off course have to transfer the open issues.)

@thomthom, As I said, it is to our benefit to keep the issues separate, in a separate repo, in a separate tracker.

> @jimfoltz: Is it a problem then if the template gets updated in the stubs repo, would you need to manually copy the changes to the sketchup-yard-template repo?

The opposite should be happening. The stubs repo is just a "carrier" for the latest template release.

> @thomthom: Yea, I can probably exclude the custom templates we use ourself. It's the "default" sub-folder which is the custom template for the docs.

And the "default" sub-folder is the ONLY custom template for the docs, currently in the stubs repo. **So all is good now.**

> @jimfoltz : Or would you just move that entire template out of the sketchup-yard-template repo to the stubs repo?

Please don't.

> @thomthom: That being said, the stubs template use just use the YARD database, so you could use that template yourself to generate stubs out of anything. 

And it works.

> @thomthom: I think with the current sketchup-yard-template repo I've so far manually kept it up to date by copy+paste. I have been meaning to automate that ...

Please do, the "assets" and "pages" folder would get copied from the stubs back to the template repo (to migrate any contibutions,) and the latest "su-template/default" folder copied over to the stubs.

What remains is a means to notify those concerned when this happens ? A stubs repo release ? A template repo release ? Both ?

**Comment by thomthom** [comment]
So, Dan, you are ok with a copy of the template be in the stubs repo? But the main tempate repo is the ruling one for all template issues?

Then we'd on our end have to make sure our tools update all points accordingly?

**Comment by DanRathbun** [comment]
YES.

**Comment by DanRathbun** [comment]
Actually, I myself created two CMD scripts, one to generate local Trimble docs form the `"su-template"` and another to generate docs from a copy named `"su-template-tweak"`, which I play with to change CSS which also required a change to two of the ERB files.
Then I modified the `".gitignore"` file to ignore this extra `"su-template-tweak"` template folder, as well as all `"*.bak"` files, so as not to submit them with PRs.

**Comment by DanRathbun** [comment]
... For now, it is easier and quicker to play around with a copy of the template in the local stubs repo-clone, even though I have also forked and cloned the template repo proper.

When I get a good handle on the YARD styling and ERB files, then I can create a proper branch of that repo, and then do proper PRs.

**Comment by thomthom** [comment]
Learning more about YARD, I find that we could build the YARD template as a gem. As long as the user have that gem install when building and in their yardopts specify the name of that gem it will all work.

If we migrated to publish the template as a gem we don't have to duplicate it here in the stubs repo.

**Comment by jimfoltz** [comment]
Didn't mean to hit close.

**Comment by jimfoltz** [comment]
i don't see much of a difference between using  a gem version of the template and just using my local clone of the repo itself.

**Comment by thomthom** [comment]
With a gem one can describe the dependencies of the stubs project as part of the `Gemfile`. Then the setup would only involve invoking Ruby to install them. Would simplify maintenance in that we don't have to copy over the template to multiple repos.

**Comment by DanRathbun** [comment]
I have not the foggiest idea how to deal with gems and Git repos locally or with my online forks. **It just doesn't seem like it would be a benefit to me.**
Sounds like I'd be opening gem archives with 7Zip and/or copying the files manually from some gem folder to my local repo folder.

You recently added Thor to the template, why not create a nifty copy command ?

**Comment by thomthom** [comment]
The Ruby gem system takes care of all of that for you.

For instance, you can install the stubs as a gem now (useful for RubyMine autocomplete). From the command line; `gem install sketchup-api-stubs`

If we made the YARD template into a gem it would become something similar, maybe; `gem install yard-sketchup-template`

From then on you only would need to use `gem update` to keep everything up to date.

If you wanted to modify the template then you would off course have to clone the repo.

Gem is Ruby's way to handle dependencies, so it makes sense to use it for these Ruby related projects that depend on each other. Plus, one can specify exactly which gems and versions is required (as I've run into a few times that YARD introduced a regression bug and I had to roll back to an older version.). By locking down the exact gems (yard, thor etc) it would become easier to install.

**Comment by jimfoltz** [comment]
I realize you are trying to lower the barriers for contributing - that's good. I am not against the idea, but speaking for myself, I would not use the gems. I am just using a `.yardopts` file to build the docs directly from my clones of the repositories.  The repositories are easily updated with git.

**Comment by thomthom** [comment]
You use the separate YARD template repo to build the docs?

That would still be possible even if it was packages as a gem though.

**Comment by jimfoltz** [comment]
> You use the separate YARD template repo to build the docs?

Yes. I have the template repo and stubs repo, but build the docs in a separate folder with this `.yardopts`

```
--title "SketchUp Ruby API Documentation"
--no-api
--no-private
--template-path ../jf-sketchup-yard-template/su-template
--template default
../jf-sketchup-api-stubs/SketchUp/**/*.rb
-
../jf-ruby-api-stubs/pages/*.md
```

**Comment by thomthom** [comment]
Gotcha - ok. then it sounds like gem-ifying the template won't break that.

**Comment by jimfoltz** [comment]
> Gotcha - ok. then it sounds like gem-ifying the template won't break that.

Right, it won't affect me at all.  I use git to manage the template version I want to build the docs for since I would already have a git prompt or gui open already.  I do not want to bring `gem` into the mix, or blindly or accidentally `gem update` because in my experience it has a tendency to  break things on windows.

**Comment by thomthom** [comment]
I think I'll create a dev branch that include the changes I had in mind. Then instead of pushing that directly I'll create a PR out of it for feedback. Just to be safe - I'm pretty sure it should affect your existing workflow though.

**Comment by DanRathbun** [comment]
> For instance, you can install the stubs as a gem now (useful for RubyMine autocomplete). From the command line; `gem install sketchup-api-stubs`

I don't use RubyMine.

And gem installs into the system ruby gems folder hierarchy, doesn't it?

I have ALL my git repos in one place beneath my "Documents" folder for easy migration to another computer. (Automatically selected by most all migration tools.) Example:
`C:\Users\Dan\Documents\GitHub\SketchUp\api\sketchup-yard-template`

I am not even using Thor, nor do I run yardoc from a Ruby shell. I use CMD batch files that I just double click.

I'm just not interested in mixing gems into things right now. I don't use the Git shell, I use the Desktop Git applet.

Sheez, just to many new stuff to learn.

**Comment by thomthom** [comment]
SketchUp's custom YARD template is now a gem: https://github.com/SketchUp/sketchup-yard-template
