### ISSUE TITLE
Sketchup::Entity#persistent_id

### ISSUE THREAD

**Issue by jonsketch** [SketchUp/ruby-api-stubs#20]
Task is to be more specific on which entities will return a unique persistent id.  Documentation should also state that a value of 0 is returned for entities that do not currently have this functionality.

**Comment by thomthom** [comment]
@jonsketch - do we have such a list internally?

**Comment by thomthom** [comment]
https://github.com/SketchUp/api-issue-tracker/issues/29#issuecomment-360201929

> I looked up the source and found that the documentation isn't accurate. The items you get PIDs from are:
> 
> * Entities that you can iterate over in a `Sketchup::Entities` collection.
> * `Sketchup::Curve`
> * `Sketchup::Page`
> * `Sketchup::Vertex`
> 
> Persistent ids are intended for things you find in the model - meaning component instances, but not definitions.
> 
> May I ask what you tried to use PIDs for component definitions for?

**Comment by thomthom** [comment]
Closing in favor of https://github.com/SketchUp/api-issue-tracker/issues/29
