### ISSUE TITLE
Create a gem with the stubs

### ISSUE THREAD

**Issue by thomthom** [SketchUp/ruby-api-stubs#21]
This might make tings simpler in distribution, (`gem install sketchup-api-stubs` for instance...). Might help with RubyMine intellisense, maybe the autoload file can be eliminated.

Ref: https://intellij-support.jetbrains.com/hc/en-us/requests/376248

**Comment by thomthom** [comment]
Just created a test gem locally on my machine, bundling up the stubs and installed it.

Then in my RubyMine project I just added `Gemfile` and added `gem 'sketchup-api-stubs'` to it - and RubyMine provided auto-complete for everything (and no more errors/warnings). I like this much better than having to include the stubs path in each project - and needing to use the `Autoload/sketchup.rb` along with littering every file with `require 'sketchup.rb'.

I'll be setting up the gemspec for the stubs and make pushing a gem part of the stubs release checklist.

**Comment by thomthom** [comment]
Published: https://rubygems.org/gems/sketchup-api-stubs

For RubyMine this helps with autocomplete;
1. Add a `Gemfile` to your project
2. Add the line `gem 'sketchup-api-stubs'`
3. Let RubyMine install the new gem dependency

**Comment by DanRathbun** [comment]
@thomthom Can the project that this issue is associated with also be closed (or set as complete) ?

* https://github.com/SketchUp/ruby-api-stubs/projects/2
Ie, I think if you drag the issue card to the Complete column then the project will be considered complete.
