### ISSUE TITLE
Force YARD to ignore README files

### ISSUE THREAD

**Issue by thomthom** [SketchUp/ruby-api-stubs#22]
Maybe our custom template can strip it out from the file list before YARD get around to process it. It would be nice to have a README with instructions for GitHub that isn't made into the index page for the docs.

**Comment by DanRathbun** [comment]
Wrong repo. (This belongs as an issue to the template repo.)

**Comment by thomthom** [comment]
GitHub will use readme files from the `.github` folder in a repo, allowing separate readme's for GitHub and the docs YARD generates. This has been done with this repo a while back.
