### ISSUE TITLE
UpperCase argument in ui.rb is preventing file from being parsed properly in NetBeans.

### ISSUE THREAD

**Issue by NeilBurkholder** [SketchUp/ruby-api-stubs#24]
The argument for UI.openURL(URL) prevents NetBeans from properly parsing the stubs file. The result is that none of the UI.methods are shown in intellisense unless the file is edited first.

**Comment by thomthom** [comment]
Good catch. Thanks for reporting. I'll make a fix for the stubs generator for this.

**Comment by thomthom** [comment]
Fixed internally, pending stubs regen.
