### ISSUE TITLE
Class / Method list pane scroll bar not displaying correctly (with DarkReader Chrome extension)

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/ruby-api-stubs#38]
Class / Method list pane (div id "nav_wrap") scroll bar not displaying correctly. No handle nor up and down arrow buttons.

This seems to be the case for all GitHub repos of Ruby projects. Ie, RubyGems pages do the same.

**Comment by thomthom** [comment]
Is this issue still current? If so, can you add a screenshot?

**Comment by DanRathbun** [comment]
YES. Still happening. (Nov 10 2017) No scrollbar. 

BUT, the culprit is **DarkReader** Chrome extension.

**WITH** ruby.sketchup.com toggled **ON**:
![noscrollbar](https://user-images.githubusercontent.com/334837/32197706-afb33034-bd9b-11e7-8c77-6cb3b857e15b.png)
The scrollbar is there but all parts of it are white so it is made invisible. If I know where the scroll handle is, I can still grab it and scroll.
If I toggle ruby.sketchup.com OFF in the **DarkReader** extension menu, the scroll bars come back on.

![toggledarkreader](https://user-images.githubusercontent.com/334837/32197963-9ccf19dc-bd9c-11e7-82b8-f9ea72c1e1f7.png)

**Comment by DanRathbun** [comment]
Going to **close** this issue as it's not YARD's fault, nor that of the SketchUp API templates fault.

**Comment by DanRathbun** [comment]
By the way,... this is fixed in the latest release of the API. The scroll bars are working again. Not sure if DarkReader was undated or what.
