### ISSUE TITLE
Can "autoload/sketchup.rb" be more dynamic ?

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/ruby-api-stubs#6]
**Can `"autoload/sketchup.rb"` be more dynamic ?**

This would prevent having to remember to add each and every stub file.
(Ie, "_Whoops! Dang! Forgot to add the new stub to the autoload file again.
Edit, Commit, Push again for one file_.")

-----
```ruby
# encoding: UTF-8
#
# "autoload/sketchup.rb"
#
# This is a file that loads the SketchUp Ruby API stub
# files for IDE autocompletion, parameter checking, etc.


  errors = {}
  errnum = 0
  reqnum = 0

  Dir::glob(["../[Ss]ketch[Uu]p/**/*.rb"]).sort.each {|rb|
    begin
      require rb
    rescue => e
      errnum += 1
      errors[rb]= e
    else
      reqnum += 1
    end
  }

  puts "Files loaded : #{reqnum}"
  puts "Error Files  : #{errnum}"
  unless errnum.zero?
    errors.each {|rb,e|
      puts "#{e.backtrace[0]}\n  #{e.inspect}\n  \"#{rb}\""
    }
  end
  puts()
```

**Comment by thomthom** [comment]
That file is there for IDE such as RubyMine to load the stubs and provide code completion. It can't do that if the require is dynamic with variable names.

We regenerate that autoload file every time we regenerate the stubs - so it's always up to date. https://github.com/SketchUp/sketchup-yard-template/blob/master/su-template/stubs/fulldoc/text/setup.rb#L24

We can add a comment in the generated file to indicate this.

**Comment by DanRathbun** [comment]
> It [_IDE_] can't do that if the require is dynamic with variable names.

I thought perhaps the IDE was running a Ruby process (ie, the "require".)

> We regenerate that autoload file every time we regenerate the stubs ...

Okay. I thought you had to add the "FrameChangeObserver" line manually. Dumb assumption from the commit message. 

**If it's auto-gen it's good.** Yea, a comment wouldn't hurt.

**Comment by thomthom** [comment]
IDE's typically run some static analysis on source code. So when there's dynamic features they tend to need help. For instance, if you create your own `attr` type function that define a method you need some IDE helper in order to let the IDE understand what it do. Some times this is in the form of doc comments. Depend on the IDE.

It's been on my list to figure out how this works in Visual Studio Code and Sublime.

**Comment by DanRathbun** [comment]
Filed issue in template repo: [#13: Add auto-generated comment to "autoload/sketchup.rb"](https://github.com/SketchUp/sketchup-yard-template/issues/13)

**Closing this issue here.**
