### ISSUE TITLE
Why are top level stub filenames all lowercase ?

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/ruby-api-stubs#7]
@thomthom: **Why are the top level stub filenames all lowercase ?**

ie:
* `"languagehandler.rb"` instead of `"LanguageHandler.rb"`
* `"string.rb"` instead of `"String.rb"`

In the "autoload/sketchup.rb" IDE support file, the files to require are correct camel case class names, but the actual files are all lowercase. This could cause problems on case-sensitive file systems.

It also causes a different sort order if a dynamic loop is used to generated the list.

-----

**_See also this Issue/question:_** [Issue #6: Can "autoload/sketchup.rb" be more dynamic ?](https://github.com/SketchUp/ruby-api-stubs/issues/6)

**Comment by thomthom** [comment]
hm.. probably due to this `.downcase` remaining: https://github.com/SketchUp/sketchup-yard-template/blob/master/su-template/stubs/fulldoc/text/setup.rb#L109

**Comment by DanRathbun** [comment]
Filed issue in template repo: [#12: Correct case of top level stub filenames](https://github.com/SketchUp/sketchup-yard-template/issues/12)

**Closing Issue here**
