### ISSUE TITLE
SketchUp Ruby API Stubs Cannot load

### ISSUE THREAD

**Issue by jhang-jhe-wei** [SketchUp/ruby-api-stubs#77]
# SketchUp Ruby API Stubs Cannot load
I want to use SketchUp Ruby API Stubs in my RSpec test, but it cannot load.
I used Gem to install it, then when I require it, some errors occurred, like this:

![image](https://user-images.githubusercontent.com/59594475/149519180-84b60543-0f98-4939-80da-c97b6c9029c7.png)
> LoadError: cannot load such file -- sketchup-api-stubs/stubs/Array.rb

After checking the source code, I found a confusing problem, the entry file `lib/sketchup-api-stubs/sketchup.rb` need to require `sketchup-api-stubs/stubs/Array.rb`,

![image](https://user-images.githubusercontent.com/59594475/149520794-aa70c140-4b3b-4a63-bf0a-3c3f9b780025.png)
> L3

but `Array.rb` is downcase in  the directory `sketchup-api-stubs/stubs/`,  so I tried to change `Array.rb` to `array.rb`, this error disappeared, but other errors occurred😥
![image](https://user-images.githubusercontent.com/59594475/149521013-b9196c7e-f8e1-42c7-8b9d-2fddbb46a64c.png)

Can anyone use this Gem?

**Comment by thomthom** [comment]
Ah, I guess you have a case sensitive filesystem?

> Can anyone use this Gem?

Yes, it's working well with VSCode+Solargraph and RuboCop for IDE insight. (Though I guess you'd run into the case sensitive filesystem issue in those scenarios as well.)

I am however curious how you were planning on using this along with tests? How would they fit into the tests?

**Comment by DanRathbun** [comment]
I find it better to name class / module filenames in the same case as they exist in the Ruby `ObjectSpace`.
I do this in my set of API refinements.

**Comment by jhang-jhe-wei** [comment]
Thanks for your reply, I have known What is wrong.
> Ah, I guess you have a case-sensitive filesystem?

You are right, I am developing my Sketchup Extension in WSL(Ubuntu), that file system is case-sensitivity.
> I am however curious how you were planning on using this along with tests? How would they fit into the tests?

Actually, It cannot do anything in tests. just share my thought...I want to develop my extension without opening Sketchup, so I search stubs about Sketchup API, because In my opinion, Stubs will return value, but it didn't. So I make some stubs in my RSpec instead, let me can write some complex calculations without opening Sketchup, for example:

![image](https://user-images.githubusercontent.com/59594475/151022398-89051467-7118-464a-8414-6ef47c8133a9.png)
It is just a converter from JSON to object. because I call `#cm` in `ColumnRebarFormModel.new`, I make `#cm` in Float class, and it will return itself. in this way, I can test this converter correctly.

**Comment by jhang-jhe-wei** [comment]
Ok, I know, Thanks for your reply.
I will change RSpec to testup-2.
